In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([[1, 2, 3]])
c = np.array([[1],
              [2],
              [3]])

print(a.shape)
print(b.shape)
print(c.shape)

(3,)
(1, 3)
(3, 1)


第一个代表的是一维数组，第二个和第三个代表的是二维矩阵。
一个[]放一个行向量，这样一行一行写过来

In [2]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(A[1, 2])
print(A[:, 1])
print(A[1, :])
print(A[:2, :2])

6
[2 5 8]
[4 5 6]
[[1 2]
 [4 5]]


A[2,1]代表的是第3行第2列，和矩阵一样。不过需要注意的是，array是从0开始编号的

In [3]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("整体平均：", np.mean(A))
print("axis=0：", np.mean(A, axis=0))
print("axis=1：", np.mean(A, axis=1))

整体平均： 5.0
axis=0： [4. 5. 6.]
axis=1： [2. 5. 8.]


axis=0 表示沿着第 0 维进行运算，并把第 0 维消掉，因此二维矩阵中得到的是“每一列的结果”。
维数，例如[1,2]，分别是第0维，第1维

In [6]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

b = np.array([[10], [20], [30]])

print("A.shape =", A.shape)
print("b.shape =", b.shape)

print(A + b)

A.shape = (3, 3)
b.shape = (3, 1)
[[11 12 13]
 [24 25 26]
 [37 38 39]]


相当于复制了好几份b，粘贴在一起，使得新的矩阵和A的大小相等